### ISSUE TITLE
Cannot "connect spotify account", 

### ISSUE THREAD

**Issue by R8s6** [Villarrealized/sonos-web#146]
Hi,

I ran the docker instance, here's my `docker-compose.yml`:

```
---
version: "2.1"
services:
  sonos-web:
    image: sonosweb/sonos-web
    container_name: sonos-web
    ports:
      - 5050:5050
    network_mode: 'host'
    restart: unless-stopped
```
I then ran `$ docker-compose up -d` on the host.

On another computer, in a browser, I visit `http://192.168.0.104:5050`, where the IP is the host running the docker.

It appears to run well, and I can play local music (on a NAS).

But when I go to Spotify and hit the "connect spotify account" button, , it would re-direct to a page like this:
```
http://localhost:5050/spotify?code=AQCjtqI0_vP4RFVKZWvzBEZe3auC4dMcH54pj76p2Isb1kHz0iDJ9nAxhpN0_Z8elJ_Jan4G-QS-GNsH19ZvUVqkRrEfZNkGR4E9kEuWiFI6u5LKoyrkXm2tEoUAZIdL7siGY7_KxxgZhmYcD1SVc3fW36sBa27SYBsOQ7-AUXglFIbPn2jOZnyDNVJqECsHmJ-Hfzn5-nf7XlbqfEwsy7uh4vsAc6VDUL43WbOwAy32v1tv2U61g9wmQB8ecDw443wKGKoqR0y_&state=
```

on Firefox I got:
```
Unable to connect

Firefox can’t establish a connection to the server at localhost:5050.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.
```

May I ask what could be the reason, and how to fix it?

Thanks a lot for this awesome project!
